global using Bud.Server.Domain.Repositories;
global using Bud.Shared.Contracts.Requests;
global using Bud.Shared.Contracts.Common;
global using SessionResponse = Bud.Shared.Contracts.Responses.SessionResponse;
global using OrganizationResponse = Bud.Shared.Contracts.Responses.Organization;
global using WorkspaceResponse = Bud.Shared.Contracts.Responses.Workspace;
global using TeamResponse = Bud.Shared.Contracts.Responses.Team;
global using CollaboratorResponse = Bud.Shared.Contracts.Responses.Collaborator;
global using MissionResponse = Bud.Shared.Contracts.Responses.Mission;
global using ObjectiveResponse = Bud.Shared.Contracts.Responses.Objective;
global using MetricResponse = Bud.Shared.Contracts.Responses.Metric;
global using MetricCheckinResponse = Bud.Shared.Contracts.Responses.MetricCheckin;
global using TemplateResponse = Bud.Shared.Contracts.Responses.MissionTemplate;
global using OrganizationSummaryResponse = Bud.Shared.Contracts.Responses.OrganizationSummaryResponse;
global using NotificationResponse = Bud.Shared.Contracts.Responses.NotificationResponse;
global using MissionProgressResponse = Bud.Shared.Contracts.Responses.MissionProgressResponse;
global using ObjectiveProgressResponse = Bud.Shared.Contracts.Responses.ObjectiveProgressResponse;
global using MetricProgressResponse = Bud.Shared.Contracts.Responses.MetricProgressResponse;
global using CollaboratorLookupResponse = Bud.Shared.Contracts.Responses.CollaboratorLookupResponse;
global using CollaboratorLeaderResponse = Bud.Shared.Contracts.Responses.CollaboratorLeaderResponse;
global using CollaboratorSubordinateResponse = Bud.Shared.Contracts.Responses.CollaboratorSubordinateResponse;
global using CollaboratorTeamResponse = Bud.Shared.Contracts.Responses.CollaboratorTeamResponse;
global using TeamEligibleForAssignmentResponse = Bud.Shared.Contracts.Responses.TeamEligibleForAssignmentResponse;
global using CollaboratorEligibleForAssignmentResponse = Bud.Shared.Contracts.Responses.CollaboratorEligibleForAssignmentResponse;
global using MyDashboardResponse = Bud.Shared.Contracts.Responses.MyDashboardResponse;
global using TeamHealthResponse = Bud.Shared.Contracts.Responses.TeamHealthResponse;
global using DashboardLeaderResponse = Bud.Shared.Contracts.Responses.DashboardLeaderResponse;
global using DashboardTeamMemberResponse = Bud.Shared.Contracts.Responses.DashboardTeamMemberResponse;
global using EngagementScoreResponse = Bud.Shared.Contracts.Responses.EngagementScoreResponse;
global using TeamIndicatorsResponse = Bud.Shared.Contracts.Responses.TeamIndicatorsResponse;
global using IndicatorResponse = Bud.Shared.Contracts.Responses.IndicatorResponse;
global using PendingTaskResponse = Bud.Shared.Contracts.Responses.PendingTaskResponse;
