global using Bud.Application.Common;
global using Bud.Application.Ports;
global using Bud.Domain.Model;
global using Bud.Domain.Repositories;
global using Bud.Shared.Contracts;
global using Bud.Shared.Contracts.Common;
global using Bud.Shared.Contracts.Requests;
global using Bud.Shared.Contracts.Responses;
global using Bud.Shared.Kernel;
global using Notification = Bud.Domain.Model.Notification;
global using CollaboratorTeam = Bud.Domain.Model.CollaboratorTeam;
