import { Plus_Jakarta_Sans } from "next/font/google";

import type { Metadata } from "next";
import "./globals.css";
import { Auth0Provider } from "@auth0/nextjs-auth0";
import { WorkspaceProvider } from "@/providers/workspace-provider";
import { NextIntlClientProvider } from "next-intl";
import QueryProvider from "@/providers/query-provider";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bud_main_font = Plus_Jakarta_Sans({ subsets: ["latin"] });

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const savedWorkspace = cookieStore.get("selectedWorkspace")?.value;

  return (
    <html lang="en">
      <body
        className={`antialiased ${bud_main_font.className} text-[#525252] font-[500]`}
      >
        <Auth0Provider>
          <NextIntlClientProvider>
            <QueryProvider>
              <WorkspaceProvider initialWorkspace={savedWorkspace}>
                {children}
              </WorkspaceProvider>
            </QueryProvider>
          </NextIntlClientProvider>
        </Auth0Provider>
      </body>
    </html>
  );
}
