import type { Metadata } from "next";
import "./globals.css";
import { Auth0Provider } from "@auth0/nextjs-auth0";
import { WorkspaceProvider } from "@/contexts/WorkspaceContext";
import { NextIntlClientProvider } from "next-intl";
import QueryProvider from "@/contexts/QueryContext";
import { cookies } from "next/headers";

import "@fontsource/crimson-pro/600.css";
import "@fontsource/plus-jakarta-sans/600.css";
import "@fontsource/plus-jakarta-sans/700.css";
import "@fontsource/inter/400.css";
import "@fontsource/inter/500.css";
import "@fontsource/inter/600.css";
import { ConfigDataProvider } from "@/contexts/ConfigDataContext";
import { AppLayout } from "@/presentation/layout/page";
import { MissionsDataProvider } from "@/contexts/MissionsDataContext";
import { ActivityDataProvider } from "@/contexts/ActivityDataContext";
import { SettingsDataProvider } from "@/contexts/SettingsDataContext";
import { IntegrationsDataProvider } from "@/contexts/IntegrationsDataContext";
import { PeopleDataProvider } from "@/contexts/PeopleDataContext";
import { SurveysDataProvider } from "@/contexts/SurveysDataContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const savedWorkspace = cookieStore.get("selectedWorkspace")?.value;

  return (
    <html lang="en">
      <body className="antialiased">
        <Auth0Provider>
          <NextIntlClientProvider>
            <QueryProvider>
              <WorkspaceProvider initialWorkspace={savedWorkspace}>
                <ConfigDataProvider>
                  <ActivityDataProvider>
                    <PeopleDataProvider>
                      <MissionsDataProvider>
                        <SurveysDataProvider>
                          <SettingsDataProvider>
                            <IntegrationsDataProvider>
                              <AppLayout>{children}</AppLayout>
                            </IntegrationsDataProvider>
                          </SettingsDataProvider>
                        </SurveysDataProvider>
                      </MissionsDataProvider>
                    </PeopleDataProvider>
                  </ActivityDataProvider>
                </ConfigDataProvider>
              </WorkspaceProvider>
            </QueryProvider>
          </NextIntlClientProvider>
        </Auth0Provider>
      </body>
    </html>
  );
}
